'use strict';
const sizes=['S','M','L','XL'];
let products=[{id:'ivory',color:'Ivory',price:500,image:'assets/elan-ivory.png',stock:{}},{id:'navy',color:'Navy',price:500,image:'assets/elan-navy.png',stock:{}},{id:'black',color:'Black',price:500,image:'assets/elan-black-correct.png',stock:{}}];
const config=window.AZURI_CONFIG||{};
const connected=Boolean(config.supabaseUrl&&config.anonKey);
const $=id=>document.getElementById(id);
const money=n=>'TT$'+Number(n).toLocaleString('en-TT',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let cart=[];try{cart=JSON.parse(localStorage.getItem('azuriBagV2'))||[];if(!Array.isArray(cart))cart=[];cart=cart.filter(i=>products.some(p=>p.id===i.id)&&sizes.includes(i.size)&&Number.isInteger(i.qty)&&i.qty>0&&i.qty<=60);}catch{}
let token=sessionStorage.getItem('azuriAdminToken')||'';
async function api(path,options={},admin=false){if(!connected)throw Error('The order service is not connected yet. Please contact Azuri.');const r=await fetch(config.supabaseUrl.replace(/\/$/,'')+path,{...options,headers:{apikey:config.anonKey,...(admin?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json',...options.headers}});const result=await r.json().catch(()=>null);if(!r.ok)throw Error(result?.message||result?.msg||result?.error_description||'Unable to complete request. Please try again.');return result;}
function notify(s){$('toast').textContent=s;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',3500);}
function saveBag(){localStorage.setItem('azuriBagV2',JSON.stringify(cart));renderBag();}
function subtotal(){return cart.reduce((n,i)=>n+products.find(p=>p.id===i.id).price*i.qty,0);}
function itemMarkup(i,controls=false){const p=products.find(p=>p.id===i.id);return `<div class="bag-item"><img src="${esc(p.image)}" alt="Élan I ${esc(p.color)}"><div><h3>Élan I · ${esc(p.color)}</h3><p>Size ${esc(i.size)} · ${money(p.price)}</p><p>${controls?`<button data-change="-1" data-id="${i.id}" data-size="${i.size}" aria-label="Decrease quantity">−</button> ${i.qty} <button data-change="1" data-id="${i.id}" data-size="${i.size}" aria-label="Increase quantity">+</button> <button data-remove="${i.id}" data-size="${i.size}">Remove</button>`:`Quantity ${i.qty} · ${money(p.price*i.qty)}`}</p></div></div>`;}
function renderBag(){$('count').textContent=cart.reduce((s,i)=>s+i.qty,0);$('bagItems').innerHTML=cart.length?cart.map(i=>itemMarkup(i,true)).join(''):'<p>Your bag is empty.</p>';$('bagTotal').textContent=money(subtotal());$('checkoutLink').hidden=!cart.length;if($('summaryItems')){$('summaryItems').innerHTML=cart.length?cart.map(i=>itemMarkup(i)).join(''):'<p>Your bag is empty. <a href="index.html#collection">Explore Élan I</a>.</p>';$('summaryTotal').textContent=money(subtotal());}}
$('bag').onclick=()=>$('bagDialog').showModal();$('closeBag').onclick=()=>$('bagDialog').close();
$('bagItems').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.id||b.dataset.remove,i=cart.find(x=>x.id===id&&x.size===b.dataset.size);if(!i)return;if(b.dataset.remove)i.qty=0;else {const qty=i.qty+Number(b.dataset.change),p=products.find(p=>p.id===id);if(qty>60||(connected&&qty>(p.stock[i.size]||0))){notify('That quantity is not available.');return;}i.qty=qty;}cart=cart.filter(x=>x.qty>0);saveBag();};
let selectedSize='S',productId=new URLSearchParams(location.search).get('product')||'ivory';if(!products.some(p=>p.id===productId))productId='ivory';
function renderProduct(){if(!$('productImage'))return;const p=products.find(x=>x.id===productId);$('productImage').src=p.image;$('productImage').alt='Élan I in '+p.color;if($('productColor'))$('productColor').textContent=p.color;if($('productTitle'))$('productTitle').textContent='Élan slim fit polo- '+p.color;$('productPrice').textContent=money(p.price);document.title='Élan I · '+p.color+' — Azuri';$('colors').innerHTML=products.map(x=>`<button type="button" data-color="${x.id}" class="${x.id===productId?'selected':''}" aria-pressed="${x.id===productId}">${esc(x.color)}</button>`).join('');$('sizes').innerHTML=sizes.map(s=>`<button type="button" data-size="${s}" class="${s===selectedSize?'selected':''}" aria-pressed="${s===selectedSize}" ${connected&&!(p.stock[s]>0)?'disabled':''}>${s}</button>`).join('');$('addBag').disabled=connected&&!(p.stock[selectedSize]>0);$('stockNote').textContent=connected?(p.stock[selectedSize]>0?'Available in your selected size.':'This size is currently unavailable.'):'Stock availability will be confirmed when ordering opens.';}
if($('colors')){$('colors').onclick=e=>{const b=e.target.closest('[data-color]');if(b){productId=b.dataset.color;history.replaceState(null,'','?product='+productId);renderProduct();}};$('sizes').onclick=e=>{const b=e.target.closest('[data-size]');if(b){selectedSize=b.dataset.size;renderProduct();}};$('addBag').onclick=()=>{const p=products.find(x=>x.id===productId),old=cart.find(x=>x.id===productId&&x.size===selectedSize),qty=(old?.qty||0)+1;if(qty>60||(connected&&qty>(p.stock[selectedSize]||0)))return notify('That quantity is not available.');if(old)old.qty++;else cart.push({id:productId,size:selectedSize,qty:1});saveBag();$('bagDialog').showModal();};}
function renderProducts(){if($('products'))$('products').innerHTML=products.map(p=>`<a class="product-card" href="product.html?product=${p.id}"><img src="${esc(p.image)}" alt="Élan I in ${esc(p.color)}"><div class="product-meta"><div><h3>Élan I</h3><p>${esc(p.color)} · Slim fit polo</p></div><span>${money(p.price)}</span></div></a>`).join('');renderProduct();renderBag();}
let orderRequestId=crypto.randomUUID();
if($('orderForm')){$('placeOrder').disabled=!connected||!cart.length;if(!connected)$('checkoutStatus').textContent='Online ordering is not open yet. Please contact Azuri to enquire.';$('orderForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return;const b=$('placeOrder');b.disabled=true;const customer=Object.fromEntries(new FormData(e.target));try{const result=await api('/rest/v1/rpc/place_order',{method:'POST',body:JSON.stringify({request_id:orderRequestId,customer,bag:cart})});cart=[];saveBag();$('orderForm').innerHTML=`<h2>Request received.</h2><p>Your reference is <strong>${esc(result.id)}</strong>.</p><p>No payment has been taken. Azuri will contact you to confirm payment and delivery.</p><a class="button" href="index.html">Return to collection</a>`;}catch(error){$('checkoutStatus').textContent=error.message;b.disabled=false;}};}
let orders=[];
async function loadAdmin(){try{const [o,p]=await Promise.all([api('/rest/v1/orders?select=*&order=created_at.desc',{},true),api('/rest/v1/products?select=*&order=id',{},true)]);orders=o;products=p;$('loginForm').hidden=true;$('adminContent').hidden=false;$('logout').hidden=false;const paid=o.filter(x=>x.status==='Paid');$('metrics').innerHTML=[['Payments received',money(paid.reduce((s,x)=>s+Number(x.total),0))],['Order requests',o.length],['Units paid',paid.reduce((s,x)=>s+x.items.reduce((n,i)=>n+i.qty,0),0)],['Available stock',p.reduce((s,x)=>s+Object.values(x.stock).reduce((a,b)=>a+Number(b),0),0)]].map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join('');$('orders').innerHTML=o.length?o.map(x=>`<tr><td>${esc(x.id.slice(0,8))}</td><td>${esc(x.customer.firstName+' '+x.customer.lastName)}</td><td>${money(x.total)}</td><td>${esc(x.status)}</td><td><button data-order="${x.id}">View</button></td></tr>`).join(''):'<tr><td colspan="5">No orders yet.</td></tr>';$('inventory').innerHTML=p.map(x=>`<form class="inventory-row" data-product="${x.id}"><strong>Élan I · ${esc(x.color)}</strong><label>Price (TTD)<input name="price" type="number" min="1" step=".01" value="${x.price}" required></label><div class="stock-inputs">${sizes.map(s=>`<label>${s}<input name="${s}" type="number" min="0" max="10000" step="1" value="${x.stock[s]||0}" required></label>`).join('')}</div><button>Save</button></form>`).join('');$('adminMessage').textContent='';}catch(e){$('adminMessage').textContent=e.message;$('loginForm').hidden=false;$('adminContent').hidden=true;}}
if($('loginForm')){if(!connected){$('adminMessage').textContent='Connect the database using SETUP.md before signing in.';$('loginForm').querySelector('button').disabled=true;}else if(token)loadAdmin();$('loginForm').onsubmit=async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{const v=Object.fromEntries(new FormData(e.target));const session=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify(v)});if(session.user?.app_metadata?.azuri_admin!==true)throw Error('This account does not have admin access.');token=session.access_token;sessionStorage.setItem('azuriAdminToken',token);e.target.reset();await loadAdmin();}catch(err){$('adminMessage').textContent=err.message;}finally{b.disabled=false;}};$('refresh').onclick=loadAdmin;$('logout').onclick=()=>{token='';sessionStorage.removeItem('azuriAdminToken');location.reload();};$('orders').onclick=e=>{const b=e.target.closest('[data-order]');if(!b)return;const o=orders.find(x=>x.id===b.dataset.order);$('orderDetails').innerHTML=`<p><strong>${esc(o.id)}</strong></p><p>${esc(o.customer.firstName+' '+o.customer.lastName)}<br>${esc(o.customer.email)}<br>${esc(o.customer.phone)}<br>${esc(o.customer.address)}, ${esc(o.customer.city)}, ${esc(o.customer.country)}</p><p>${o.items.map(i=>`${i.qty} × Élan I ${esc(i.color)} / ${esc(i.size)} · ${money(i.price*i.qty)}`).join('<br>')}</p><p>Merchandise subtotal: ${money(o.total)}<br>Delivery quoted separately<br>${esc(new Date(o.created_at).toLocaleString())}</p><label>Status<select id="orderStatus">${['Pending','Paid','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></label><p id="statusError" role="status"></p><button class="button" id="saveStatus">Save status</button>`;$('saveStatus').onclick=async()=>{const b=$('saveStatus');b.disabled=true;try{await api('/rest/v1/rpc/set_order_status',{method:'POST',body:JSON.stringify({order_id:o.id,new_status:$('orderStatus').value})},true);$('orderDialog').close();await loadAdmin();}catch(e){$('statusError').textContent=e.message;}finally{b.disabled=false;}};$('orderDialog').showModal();};$('closeOrder').onclick=()=>$('orderDialog').close();$('inventory').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{const v=Object.fromEntries(new FormData(f)),stock=Object.fromEntries(sizes.map(s=>[s,Number(v[s])]));await api('/rest/v1/products?id=eq.'+encodeURIComponent(f.dataset.product),{method:'PATCH',body:JSON.stringify({price:Number(v.price),stock})},true);notify('Stock and price updated.');await loadAdmin();}catch(err){$('adminMessage').textContent=err.message;}finally{b.disabled=false;}};}
renderProducts();if(connected&&!$('loginForm'))api('/rest/v1/products?select=*&order=id').then(p=>{if(p.length!==3)throw Error('The collection is not configured.');products=p;renderProducts();}).catch(e=>{notify('Live stock could not be loaded. Please try again.');if($('addBag'))$('addBag').disabled=true;if($('placeOrder'))$('placeOrder').disabled=true;});
