/* Admin-only catalogue controls; writes require the Supabase migration. */
(function(){
 const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 window.renderAzuriProducts=rows=>{
 const ready=rows.every(p=>p.product_name&&p.sizes);
 document.getElementById('catalogueStatus').textContent=ready?'New variants are drafts. The storefront continues to show the current Élan collection.':'Run multi-product-migration.sql in Supabase to enable product management. Existing inventory remains available below.';
 document.getElementById('productCreate').querySelector('button').disabled=!ready;
 const groups=new Map();for(const p of rows){if(!p.product_name)continue;if(!groups.has(p.product_name))groups.set(p.product_name,[]);groups.get(p.product_name).push(p);}
 document.getElementById('productManager').innerHTML=[...groups].map(([name,variants])=>`<section class="catalogue-group"><h3>${html(name)}</h3>${variants.map(p=>`<form class="inventory-row" data-variant="${html(p.id)}"><p>${html(p.color)} · ${p.active?'Active':'Draft'} · ${html(p.id)}</p><label>Product name<input name="product_name" value="${html(p.product_name)}" required maxlength="80"></label><label>Colour<input name="color" value="${html(p.color)}" required maxlength="80"></label><label>Image path or HTTPS URL<input name="image" value="${html(p.image)}" required></label><label>Price (TTD)<input name="price" type="number" min=".01" step=".01" value="${p.price}" required></label><div class="stock-inputs">${p.sizes.map(size=>`<label>${html(size)}<input data-stock="${html(size)}" type="number" min="0" max="10000" step="1" value="${p.stock[size]||0}" required></label>`).join('')}</div><label>Status<select name="active"><option value="false" ${!p.active?'selected':''}>Draft</option><option value="true" ${p.active?'selected':''}>Active</option></select></label><button>Save variant</button></form>`).join('')}</section>`).join('');
 };
 async function write(form,payload){const button=form.querySelector('button');button.disabled=true;try{await api('/rest/v1/rpc/save_product_variant',{method:'POST',body:JSON.stringify({variant:payload})},true);await loadAdmin();notify('Product variant saved.');}catch(e){document.getElementById('adminMessage').textContent=e.message;}finally{button.disabled=false;}}
 document.getElementById('productManager').onsubmit=e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f)),stock={};for(const input of f.querySelectorAll('[data-stock]'))stock[input.dataset.stock]=Number(input.value);write(f,{...v,id:f.dataset.variant,price:Number(v.price),active:v.active==='true',sizes:Object.keys(stock),stock});};
 document.getElementById('productCreate').onsubmit=async e=>{e.preventDefault();const f=e.target,v=Object.fromEntries(new FormData(f)),sizes=v.size_list.split(',').map(s=>s.trim()).filter(Boolean);if(!sizes.length||new Set(sizes).size!==sizes.length){document.getElementById('adminMessage').textContent='Enter distinct sizes.';return;}await write(f,{...v,create_new:true,price:Number(v.price),sizes,stock:Object.fromEntries(sizes.map(s=>[s,0])),active:false});};
})();
